package:
  name: phylobayes_mpi
  version: 1.8

source:
  fn: 2f5deee75687a51225a0bd4705c93f3292f85cdb.tar.gz
  url: https://github.com/bayesiancook/pbmpi/archive/2f5deee75687a51225a0bd4705c93f3292f85cdb.tar.gz
  sha256: dfd7276593e41c55faf57a7c4dc8e1fa86a919891001324df2350f394dc18fdf


requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - mpich
  run:
    - mpich

test:
  commands:
    - pb_mpi -v > /dev/null

about:
  home: https://github.com/bayesiancook/pbmpi
  license: GPLv2
  summary: Phylogenetics - Bayesian phylogenetic reconstruction using mixture models
