package:
  name: agalma
  version: 1.0.1

source:
  fn: agalma-1.0.1.zip
  url: https://bitbucket.org/caseywdunn/agalma/get/release-1.0.1.zip
  sha256: 8442607caec78f127bf716977bad49f8deb2b79fc1c6732ae3d23afbfac9e2c5

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - biolite ==1.0.0
    - blast ==2.5.0
    - bowtie2 ==2.3.0
    - fastqc ==0.11.5
    - gblocks ==0.91b
    - mafft ==7.305
    - mcl ==14.137
    - parallel ==20160622
    - raxml ==8.2.9
    - rsem ==1.3.0
    - rsem-eval ==1.9
    - samtools ==1.2
    - transdecoder ==2.1.0
    - trinity ==2.3.2

test:
  imports:
    - agalma
  commands:
    - agalma -h

about:
  home: https://bitbucket.org/caseywdunn/agalma
  license: GPLv3
  summary: An automated phylogenomics pipeline.
